name: CI

permissions:
  contents: read

on: [pull_request, push]

jobs:
  build:
    name: Run in mode ${{ matrix.profile }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
        profile: [debug, release]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Build
        run: |
          cd RustDataFusion
          cargo build --profile ${{ matrix.profile }}

      - name: Run
        run: |
          cargo run --profile ${{ matrix.profile }}
